name: mantarix_video
description: Mantarix Video control
repository: https://github.com/mantarix-dev/mantarix/packages/mantarix_video
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.16.0
  media_kit: ^1.2.0
  media_kit_video: ^1.3.0
  media_kit_libs_video: ^1.0.6

  mantarix:
    path: ../mantarix/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0