name: mantarix_lightsensor
description: LightSensor control
repository: https://github.com/mantarix-dev/mantarix/packages/mantarix_lightsensor
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  ambient_light: ^0.0.4

  mantarix:
    path: ../mantarix/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0