name: mantarix_geolocator
description:  Mantarix Geolocator control
repository: https://github.com/mantarix-dev/mantarix/packages/mantarix_geolocator
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  geolocator: ^13.0.1
  collection: ^1.16.0

  mantarix:
    path: ../mantarix/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
